- hosts: nectar
  vars_files:
    - variables/website.yml
  vars:
    ansible_user: ubuntu
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: ~/.ssh/comp90024-group19.pem
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  gather_facts: true

  roles:
    - role: proxy
    - role: install
    - role: mount_volumes
    - role: website
